"""add_image_url_to_player

Revision ID: 02c42f82e768
Revises: 55bdd257430f
Create Date: 2026-02-13 00:01:22.368856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c42f82e768'
down_revision: Union[str, Sequence[str], None] = '55bdd257430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'image_url')
    # ### end Alembic commands ###
