"""enhance_models_for_frontend

Revision ID: e8247499f40c
Revises: 9dbc403edecb
Create Date: 2026-02-13 00:34:39.271897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8247499f40c'
down_revision: Union[str, Sequence[str], None] = '9dbc403edecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('matches', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('runs', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('wickets', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('average', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('players', sa.Column('strike_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('players', sa.Column('economy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('color', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('secondary_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'secondary_color')
    op.drop_column('teams', 'primary_color')
    op.drop_column('teams', 'color')
    op.drop_column('teams', 'logo_url')
    op.drop_column('players', 'economy')
    op.drop_column('players', 'strike_rate')
    op.drop_column('players', 'average')
    op.drop_column('players', 'wickets')
    op.drop_column('players', 'runs')
    op.drop_column('players', 'matches')
    op.drop_column('players', 'age')
    op.drop_column('players', 'nationality')
    # ### end Alembic commands ###
